

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- task: TerraformInstaller@1
  inputs:
    terraformVersion: 'latest'

- task: TerraformTaskV4@4
  name: terraform_init
  inputs:
    provider: 'azurerm'
    command: 'init'
    backendServiceArm: 'cicd'
    backendAzureRmResourceGroupName: 'terra'
    backendAzureRmStorageAccountName: 'terra056'
    backendAzureRmContainerName: 'terraa'
    backendAzureRmKey: 'terraform.tfstate'

- task: TerraformTaskV4@4
  name: terraform_validate
  inputs:
    provider: 'azurerm'
    command: 'validate'

- task: TerraformTaskV4@4
  name: terraform_plan
  inputs:
    provider: 'azurerm'
    command: 'plan'
    environmentServiceNameAzureRM: 'cicd'
- task: TerraformTaskV4@4
  name: terraform_apply
  inputs:
    provider: 'azurerm'
    command: 'apply'
    environmentServiceNameAzureRM: 'cicd'